name: 🛝 Build & Publish Slides

on: push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v6

    - name: Install just
      uses: taiki-e/install-action@just

    - name: Copy resources
      run: just init-build

    - name: Create HTML version of slides
      uses: docker://marpteam/marp-cli:latest
      env:
        MARP_USER: root:root
      with:
        args: >
          --html
          -o build/index.html
          ICOtest.md

    - name: Upload slides to GitHub pages
      uses: actions/upload-pages-artifact@v4
      with:
        path: build

  deploy:
    name: Publish

    needs: build
    runs-on: ubuntu-latest

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an
                        # appropriate source
    steps:

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
